import express, { Request, Response } from "express";
import { ApiResponseDto } from "../../dto/api-response.dto";
import { generateStrongPassword } from "../../services/util";
import { sendEmail } from "../../services/mailer";
import { COMPANY_LOGIN_DETAIL_TEMPLATE } from "../../services/email-templates";

const router = express.Router();

router.post("/api/test", async (req: Request, res: Response) => {
  try {
    const name = "Test Company";
    const { emailAddress } = req.body;
    const passwordData = await generateStrongPassword(8);
    const autoGeneratedStrongPass = passwordData.passwordString;

    // * Sending email to user with login details
    const emailHtmlContent = COMPANY_LOGIN_DETAIL_TEMPLATE.replace(
      "{{companyName}}",
      name
    )
      .replace("{{companyEmail}}", emailAddress)
      .replace("{{password}}", autoGeneratedStrongPass)
      .replace("{{loginURL}}", process.env.LOGIN_URL);

    await sendEmail(
      emailAddress,
      `Successful Company Registration`,
      emailHtmlContent
    );

    return res
      .status(200)
      .send(new ApiResponseDto(false, "Company created successfully", [], 200));
  } catch (error) {
    console.error("Error occurred during creating-company", error);
    return res
      .status(500)
      .send(
        new ApiResponseDto(
          true,
          "Something wen't wrong while creating company",
          [],
          500
        )
      );
  }
});

export { router as testRouter };
