export enum UserType {
  VISITOR = "VISITOR",
  EMPLOYEE = "EMPLOYEE",
  ADMIN = "ADMIN",
}

export enum GENDER {
  MALE = "MALE",
  FEMALE = "FEMALE",
}

export enum EventType {
  FORGOT_PASSWORD = "FORGOT_PASSWORD",
  EMAIL_VERIFICATION = "EMAIL_VERIFICATION",
  MULTIFACTOR_AUTH = "MULTIFACTOR_AUTH",
  MOBILENO_VERIFICATION = "MOBILENO_VERIFICATION",
}

export enum DomainType {
  EMAIL = "EMAIL",
  SMS = "SMS",
  BOTH = "BOTH",
}
